// Action types for fetching defaulters list
export const GET_DEFAULTERS_LIST = "GET_DEFAULTERS_LIST";
export const GET_DEFAULTERS_LIST_SUCCESS = "GET_DEFAULTERS_LIST_SUCCESS";
export const GET_DEFAULTERS_LIST_FAIL = "GET_DEFAULTERS_LIST_FAIL";

// Action types for updating unpaid fee challans
export const UPDATE_DEFAULTERS_LIST = "UPDATE_DEFAULTERS_LIST";
export const UPDATE_DEFAULTERS_LIST_SUCCESS = "UPDATE_DEFAULTERS_LIST_SUCCESS";
export const UPDATE_DEFAULTERS_LIST_FAIL = "UPDATE_DEFAULTERS_LIST_FAIL";
