/* OFFERED TESTS */
export const GET_CHALLANS = "GET_CHALLANS";
export const GET_CHALLANS_SUCCESS = "GET_CHALLANS_SUCCESS";
export const GET_CHALLANS_FAIL = "GET_CHALLANS_FAIL";

export const ADD_NEW_CHALLAN = "ADD_NEW_CHALLAN";
export const ADD_CHALLAN_SUCCESS = "ADD_CHALLAN_SUCCESS";
export const ADD_CHALLAN_FAIL = "ADD_CHALLAN_FAIL";

export const UPDATE_CHALLAN = "UPDATE_CHALLAN";
export const UPDATE_CHALLAN_SUCCESS = "UPDATE_CHALLAN_SUCCESS";
export const UPDATE_CHALLAN_FAIL = "UPDATE_CHALLAN_FAIL";

export const DELETE_CHALLAN = "DELETE_CHALLAN";
export const DELETE_CHALLAN_SUCCESS = "DELETE_CHALLAN_SUCCESS";
export const DELETE_CHALLAN_FAIL = "DELETE_CHALLAN_FAIL";

export const ADD_CHALLAN_WITH_IMAGE = "ADD_CHALLAN_WITH_IMAGE";
export const ADD_CHALLAN_WITH_IMAGE_SUCCESS = "ADD_CHALLAN_WITH_IMAGE_SUCCESS";
export const ADD_CHALLAN_WITH_IMAGE_FAIL = "ADD_CHALLAN_WITH_IMAGE_FAIL";
