/* SCHOOL PROFILE */
export const GET_SCHOOL_PROFILE = "GET_SCHOOL_PROFILE";
export const GET_SCHOOL_PROFILE_SUCCESS = "GET_SCHOOL_PROFILE_SUCCESS";
export const GET_SCHOOL_PROFILE_FAIL = "GET_SCHOOL_PROFILE_FAIL";


export const UPDATE_SCHOOL_PROFILE = "UPDATE_SCHOOL_PROFILE";
export const UPDATE_SCHOOL_PROFILE_SUCCESS =
  "UPDATE_SCHOOL_PROFILE_SUCCESS";
export const UPDATE_SCHOOL_PROFILE_FAIL = "UPDATE_SCHOOL_PROFILE_FAIL";

