export const GET_STUDENTS_BY_CLASS = "GET_STUDENTS_BY_CLASS";
export const GET_STUDENTS_BY_CLASS_SUCCESS = "GET_STUDENTS_BY_CLASS_SUCCESS";
export const GET_STUDENTS_BY_CLASS_FAIL = "GET_STUDENTS_BY_CLASS_FAIL";
export const ADD_ATTENDENCE = "ADD_ATTENDENCE";
export const ADD_ATTENDENCE_SUCCESS = "ADD_ATTENDENCE_SUCCESS";
export const ADD_ATTENDENCE_FAIL = "ADD_ATTENDENCE_FAIL";


export const GET_STUDENTS_ATTENDENCE = "GET_STUDENTS_ATTENDENCE";
export const GET_STUDENTS_ATTENDENCE_SUCCESS = "GET_STUDENTS_ATTENDENCE_SUCCESS";
export const GET_STUDENTS_ATTENDENCE_FAIL = "GET_STUDENTS_ATTENDENCE_FAIL";