/* SCHOOL FEE */
export const GET_SCHOOL_FEE = "GET_SCHOOL_FEE";
export const GET_SCHOOL_FEE_SUCCESS = "GET_SCHOOL_FEE_SUCCESS";
export const GET_SCHOOL_FEE_FAIL = "GET_SCHOOL_FEE_FAIL";


export const UPDATE_SCHOOL_FEE = "UPDATE_SCHOOL_FEE";
export const UPDATE_SCHOOL_FEE_SUCCESS =
  "UPDATE_SCHOOL_FEE_SUCCESS";
export const UPDATE_SCHOOL_FEE_FAIL = "UPDATE_SCHOOL_FEE_FAIL";

