/* SCHOOL GRADES */
export const GET_SCHOOL_GRADES = "GET_SCHOOL_GRADES";
export const GET_SCHOOL_GRADES_SUCCESS = "GET_SCHOOL_GRADES_SUCCESS";
export const GET_SCHOOL_GRADES_FAIL = "GET_SCHOOL_GRADES_FAIL";


export const UPDATE_SCHOOL_GRADES = "UPDATE_SCHOOL_GRADES";
export const UPDATE_SCHOOL_GRADES_SUCCESS =
  "UPDATE_SCHOOL_GRADES_SUCCESS";
export const UPDATE_SCHOOL_GRADES_FAIL = "UPDATE_SCHOOL_GRADES_FAIL";

