/* SCHOOL SUBJECTS */
export const GET_SCHOOL_SUBJECTS = "GET_SCHOOL_SUBJECTS";
export const GET_SCHOOL_SUBJECTS_SUCCESS = "GET_SCHOOL_SUBJECTS_SUCCESS";
export const GET_SCHOOL_SUBJECTS_FAIL = "GET_SCHOOL_SUBJECTS_FAIL";

export const GET_CLASS_SUBJECTS = "GET_CLASS_SUBJECTS";
export const GET_CLASS_SUBJECTS_SUCCESS = "GET_CLASS_SUBJECTS_SUCCESS";
export const GET_CLASS_SUBJECTS_FAIL = "GET_CLASS_SUBJECTS_FAIL";

export const UPDATE_SCHOOL_SUBJECTS = "UPDATE_SCHOOL_SUBJECTS";
export const UPDATE_SCHOOL_SUBJECTS_SUCCESS =
  "UPDATE_SCHOOL_SUBJECTS_SUCCESS";
export const UPDATE_SCHOOL_SUBJECTS_FAIL = "UPDATE_SCHOOL_SUBJECTS_FAIL";

export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL";