/* STUDENT PROFILE */
export const GET_STUDENT_PROFILE = "GET_STUDENT_PROFILE";
export const GET_STUDENT_PROFILE_SUCCESS = "GET_STUDENT_PROFILE_SUCCESS";
export const GET_STUDENT_PROFILE_FAIL = "GET_STUDENT_PROFILE_FAIL";


export const UPDATE_STUDENT_PROFILE = "UPDATE_STUDENT_PROFILE";
export const UPDATE_STUDENT_PROFILE_SUCCESS =
  "UPDATE_STUDENT_PROFILE_SUCCESS";
export const UPDATE_STUDENT_PROFILE_FAIL = "UPDATE_STUDENT_PROFILE_FAIL";

