export const GET_EMPLOYEES_BY_SCHOOL = "GET_EMPLOYEES_BY_SCHOOL";
export const GET_EMPLOYEES_BY_SCHOOL_SUCCESS = "GET_EMPLOYEES_BY_SCHOOL_SUCCESS";
export const GET_EMPLOYEES_BY_SCHOOL_FAIL = "GET_EMPLOYEES_BY_SCHOOL_FAIL";
export const ADD_EMPLOYEES_ATTENDENCE = "ADD_EMPLOYEES_ATTENDENCE";
export const ADD_EMPLOYEES_ATTENDENCE_SUCCESS = "ADD_EMPLOYEES_ATTENDENCE_SUCCESS";
export const ADD_EMPLOYEES_ATTENDENCE_FAIL = "ADD_EMPLOYEES_ATTENDENCE_FAIL";

export const GET_EMPLOYEES_ATTENDENCE = "GET_EMPLOYEES_ATTENDENCE";
export const GET_EMPLOYEES_ATTENDENCE_SUCCESS = "GET_EMPLOYEES_ATTENDENCE_SUCCESS";
export const GET_EMPLOYEES_ATTENDENCE_FAIL = "GET_EMPLOYEES_ATTENDENCE_FAIL";
  